[package]
name = "demo-python-with-rust"
version = "0.1.0"
authors = ["ban367 <ban.yamaguchi@ghelia.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpython = "0.5"
